#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.1                         #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -fPIC -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/
DEP_RELEASE = 
OUT_RELEASE = bin/CaveSurvey


OBJ_RELEASE = $(OBJDIR_RELEASE)/src/Shot.o $(OBJDIR_RELEASE)/src/Station.o $(OBJDIR_RELEASE)/src/dataFun.o $(OBJDIR_RELEASE)/src/main.o $(OBJDIR_RELEASE)/src/surveyPlot.o $(OBJDIR_RELEASE)/src/svgMap.o $(OBJDIR_RELEASE)/src/userInterface.o $(OBJDIR_RELEASE)/src/blenderOutputs.o

all:  release

clean:  clean_release

before_release: 
	test -d bin/ || mkdir -p bin/
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/Shot.o: src/Shot.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Shot.cpp -o $(OBJDIR_RELEASE)/src/Shot.o

$(OBJDIR_RELEASE)/src/Station.o: src/Station.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Station.cpp -o $(OBJDIR_RELEASE)/src/Station.o

$(OBJDIR_RELEASE)/src/dataFun.o: src/dataFun.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/dataFun.cpp -o $(OBJDIR_RELEASE)/src/dataFun.o

$(OBJDIR_RELEASE)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.o

$(OBJDIR_RELEASE)/src/surveyPlot.o: src/surveyPlot.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/surveyPlot.cpp -o $(OBJDIR_RELEASE)/src/surveyPlot.o

$(OBJDIR_RELEASE)/src/svgMap.o: src/svgMap.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/svgMap.cpp -o $(OBJDIR_RELEASE)/src/svgMap.o

$(OBJDIR_RELEASE)/src/userInterface.o: src/userInterface.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/userInterface.cpp -o $(OBJDIR_RELEASE)/src/userInterface.o

$(OBJDIR_RELEASE)/src/blenderOutputs.o: src/blenderOutputs.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/blenderOutputs.cpp -o $(OBJDIR_RELEASE)/src/blenderOutputs.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY:  before_release after_release clean_release